const {
    T_SPAWN,
    T_POPULATE_INITIAL_GROUPS,
    T_POPULATE_GROUPS_FROM_PROFILE,
    T_FILLUP,
    T_EVALUATE_THREAT_DANGEROSITY,
    T_DESTROY_TARGET,
    T_ASSEMBLE_DEFENSE_GROUP,
    T_BUILD_CONSTRUCTION_SITES,
    A_HARVEST,
    A_HARVEST_FOREVER,
    A_HAUL,
    A_UPGRADE,
    A_HEAL,
    A_MOVE,
    A_RANGED_ATTACK,
    A_BUILD,
    A_REPAIR,
    A_FETCH,
    A_SUPERFETCH,
    A_CARRY,
} = require('constants');

module.exports = {
    [T_SPAWN]: require('tasks.actor.Spawn'),
    [T_POPULATE_INITIAL_GROUPS]: require('tasks.architect.PopulateInitialGroups'),
    [T_POPULATE_GROUPS_FROM_PROFILE]: require('tasks.architect.PopulateGroupsFromProfile'),
    [T_FILLUP]: require('tasks.manager.FillUp'),
    [T_EVALUATE_THREAT_DANGEROSITY]: require('tasks.manager.EvaluateThreatDangerosity'),
    [T_DESTROY_TARGET]: require('tasks.manager.DestroyTarget'),
    [T_ASSEMBLE_DEFENSE_GROUP]: require('tasks.manager.AssembleDefenseGroup'),
    [T_BUILD_CONSTRUCTION_SITES]: require('tasks.manager.BuildConstructionSites'),
    [A_HARVEST]: require('tasks.creepActions.Harvest'),
    [A_HARVEST_FOREVER]: require('tasks.creepActions.HarvestForever'),
    [A_HAUL]: require('tasks.creepActions.Haul'),
    [A_FETCH]: require('tasks.creepActions.Fetch'),
    [A_SUPERFETCH]: require('tasks.creepActions.SuperFetch'),
    [A_CARRY]: require('tasks.creepActions.Carry'),
    [A_UPGRADE]: require('tasks.creepActions.Upgrade'),
    [A_HEAL]: require('tasks.creepActions.Heal'),
    [A_MOVE]: require('tasks.creepActions.Move'),
    [A_RANGED_ATTACK]: require('tasks.creepActions.RangedAttack'),
    [A_BUILD]: require('tasks.creepActions.Build'),
    [A_REPAIR]: require('tasks.creepActions.Repair')
};
